dataset = https://www.kaggle.com/georgesaavedra/covid19-dataset

1. Hvilken m√•ned var der flest smittede af corona for hvert land (location)?
2. Hvilket land i europa har test flest personer pr. tusinde indbyggere (total_tests_per_thousand), siden juli 2021 til nu?

In [16]:
import pandas as pd

corona = pd.read_csv('./owid-covid-data.csv',header=0, sep=',')

countries = corona[corona['continent'] == 'North America']

countries

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
4423,AIA,North America,Anguilla,2020-03-28,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.88,NaN,NaN,NaN,NaN,NaN
4424,AIA,North America,Anguilla,2020-03-29,2.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.88,NaN,NaN,NaN,NaN,NaN
4425,AIA,North America,Anguilla,2020-03-30,2.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.88,NaN,NaN,NaN,NaN,NaN
4426,AIA,North America,Anguilla,2020-03-31,2.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.88,NaN,NaN,NaN,NaN,NaN
4427,AIA,North America,Anguilla,2020-04-01,2.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,81.88,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157991,USA,North America,United States,2022-03-01,79091361.0,47031.0,62331.429,952423.0,1691.0,1830.000,...,19.1,24.6,NaN,2.77,78.86,0.926,NaN,NaN,NaN,NaN
157992,USA,North America,United States,2022-03-02,79143716.0,52355.0,57824.857,954518.0,2095.0,1725.000,...,19.1,24.6,NaN,2.77,78.86,0.926,NaN,NaN,NaN,NaN
157993,USA,North America,United States,2022-03-03,79196008.0,52292.0,55673.857,956261.0,1743.0,1553.714,...,19.1,24.6,NaN,2.77,78.86,0.926,NaN,NaN,NaN,NaN
157994,USA,North America,United States,2022-03-04,79250509.0,54501.0,52764.286,958144.0,1883.0,1497.857,...,19.1,24.6,NaN,2.77,78.86,0.926,NaN,NaN,NaN,NaN
157995,USA,North America,United States,2022-03-05,79265726.0,15217.0,47989.857,958437.0,293.0,1425.714,...,19.1,24.6,NaN,2.77,78.86,0.926,NaN,NaN,NaN,NaN